const SUCCESS_CODE_OK = 200;
const SUCCESS_CODE_CREATED = 201;
const ERROR_CODE_BAD_REQUEST = 400;
const MONGO_DUPLACATE_ERROR_CODE = 11000;
const ERROR_CODE_INTERNAL_SERVER_ERROR = 500;

module.exports = {
  SUCCESS_CODE_OK,
  SUCCESS_CODE_CREATED,
  ERROR_CODE_BAD_REQUEST,
  MONGO_DUPLACATE_ERROR_CODE,
  ERROR_CODE_INTERNAL_SERVER_ERROR,
};
